image: gcc:latest

variables:
  cmake: "cmake-3.26.2-linux-x86_64/bin/cmake"
  ctest: "cmake-3.26.2-linux-x86_64/bin/ctest"
  build-dir: "3ccodelib-build-release"

before_script:
  - apt-get update
  - wget -nv https://github.com/Kitware/CMake/releases/download/v3.26.2/cmake-3.26.2-linux-x86_64.tar.gz
  - tar xf cmake-3.26.2-linux-x86_64.tar.gz

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-lib:       # This job runs in the build stage, which runs first.
  stage: build
  artifacts:
    paths:
      -  "${build-dir}/"
    untracked: false
    when: on_success
  only: 
      - master
  script:
    - $cmake -B "3ccodelib-build-release" -DCMAKE_BUILD_TYPE=Release
    - $cmake --build "3ccodelib-build-release" --target all -j 3

ctest-test-job:   
  stage: test    
  only:
    - master
  needs:
    -  job: build-lib
       artifacts: true
  dependencies:
    - "build-lib"
  script:
    - $ctest -C Release --test-dir "3ccodelib-build-release"

deploy-job:      
  stage: deploy  
  only:
    - master
  needs:
    - job: ctest-test-job
      artifacts: false
  environment: production
  script: 
    - $cmake -B "3ccodelib-build-release" -DCMAKE_BUILD_TYPE=Release
    - $cmake --build "3ccodelib-build-release" --target all -j 3
  artifacts:
    paths:
      - "${build-dir}/*.a"
      - "${build-dir}/*.so"
    when: on_success
    expire_in: 30 days