image: gcc:latest

variables:
  cmake: "cmake-3.26.2-linux-x86_64/bin/cmake"
  ctest: "cmake-3.26.2-linux-x86_64/bin/ctest"
  build_dir: "3ccodelib-build-release"

before_script:
  - apt-get update
  - apt-get install libx11-dev xserver-xorg-dev xorg-dev
  - wget -nv https://github.com/Kitware/CMake/releases/download/v3.26.2/cmake-3.26.2-linux-x86_64.tar.gz
  - tar xf cmake-3.26.2-linux-x86_64.tar.gz

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-lib:
  stage: build
  artifacts:
    expire_in: 1 hour
    paths:
      -  "${build_dir}/"
    untracked: false
    when: on_success
  only: 
      - master
  script:
    - $cmake -B "${build_dir}" -DCMAKE_BUILD_TYPE=Release
    - $cmake --build "${build_dir}" --target all -j 3

ctest-test-job:   
  stage: test    
  only:
    - master
  needs:
    -  job: build-lib
       artifacts: true
  dependencies:
    - "build-lib"
  script:
    - $ctest --verbose -C Release --test-dir "${build_dir}"

deploy-job:      
  stage: deploy  
  only:
    - master
  needs:
    - job: ctest-test-job
      artifacts: false
  environment: production
  script: 
    - $cmake -B "${build_dir}" -DCMAKE_BUILD_TYPE=Release
    - $cmake --build "${build_dir}" --target all -j 3
  artifacts:
    paths:
      - "${build_dir}/*.a"
      - "${build_dir}/*.so"
    when: on_success
    expire_in: 30 days