image: gcc:latest

variables:
  cmake: "cmake-3.26.2-linux-x86_64/bin/cmake"
  ctest: "cmake-3.26.2-linux-x86_64/bin/ctest"

before_script:
  - apt-get update
  - wget -nv https://github.com/Kitware/CMake/releases/download/v3.26.2/cmake-3.26.2-linux-x86_64.tar.gz
  - tar xf cmake-3.26.2-linux-x86_64.tar.gz

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-lib:       # This job runs in the build stage, which runs first.
  stage: build
  only: 
      - master
  script:
    - echo "Compiling the code..."
    - $cmake -B "3ccodelib-build-release" -DCMAKE_BUILD_TYPE=Release
    - $cmake --build "3ccodelib-build-release" --target 3C-code -j 3
    - echo "Compile complete."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - $ctest -C Release --test-dir "3ccodelib-build-release"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Nothing to do here..."